FROM registry.access.redhat.com/ubi9/go-toolset:1.22 AS golang

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.0
RUN go install gotest.tools/gotestsum@latest
